"""initial schema

Revision ID: d6e2f5bdaa4f
Revises:
Create Date: 2026-09-18 13:22:38.806942

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6e2f5bdaa4f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("cognito_subject", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "DISABLED", name="user_status"), nullable=False),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_utc", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cognito_subject"),
    )
    op.create_index("uq_users_email", "users", ["email"], unique=True)
    op.create_table(
        "coach_check_ins",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=False),
        sa.Column("week_label", sa.String(length=64), nullable=False),
        sa.Column("range_label", sa.String(length=64), nullable=False),
        sa.Column("status", sa.Enum("NEEDS_REVIEW", "REVIEWED", name="check_in_status"), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("pipeline", sa.JSON(), nullable=False),
        sa.Column("suggested_questions", sa.JSON(), nullable=False),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_coach_check_ins_owner_created", "coach_check_ins", ["owner_id", "created_utc"], unique=False
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "equipment",
            sa.Enum(
                "barbell",
                "dumbbell",
                "cable",
                "machine",
                "bodyweight",
                "kettlebell",
                "band",
                name="equipment",
            ),
            nullable=False,
        ),
        sa.Column("muscles", sa.JSON(), nullable=False),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_exercises_owner_name", "exercises", ["owner_id", "name"], unique=False)
    op.create_table(
        "food_entries",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column(
            "meal", sa.Enum("breakfast", "lunch", "dinner", "snacks", name="meal_type"), nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("amount_label", sa.String(length=64), nullable=False),
        sa.Column("source", sa.Enum("DATABASE", "CUSTOM", "QUICK_ADD", name="food_source"), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("protein", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("carbs", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("fat", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_food_entries_owner_date", "food_entries", ["owner_id", "log_date"], unique=False)
    op.create_table(
        "foods",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column("serving_size", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "serving_unit",
            sa.Enum(
                "g", "ml", "piece", "bowl", "plate", "cup", "slice", "tbsp", "scoop", name="serving_unit"
            ),
            nullable=False,
        ),
        sa.Column("serving_weight_g", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("protein", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("carbs", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("fat", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("fibre_g", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("sugar_g", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("sodium_mg", sa.Numeric(precision=7, scale=1), nullable=True),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_foods_owner_name", "foods", ["owner_id", "name"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("height_cm", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("goal", sa.Enum("LOSE", "MAINTAIN", "GAIN", name="profile_goal"), nullable=False),
        sa.Column("weekly_rate_kg", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("training_days_per_week", sa.Integer(), nullable=False),
        sa.Column("target_calories", sa.Integer(), nullable=False),
        sa.Column("target_protein_g", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("target_carbs_g", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("target_fat_g", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "weigh_ins",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("uq_weigh_ins_owner_date", "weigh_ins", ["owner_id", "log_date"], unique=True)
    op.create_table(
        "workout_plan_entries",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("week_label", sa.String(length=64), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_workout_plan_owner_day", "workout_plan_entries", ["owner_id", "day_of_week"], unique=True
    )
    op.create_table(
        "coach_messages",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("check_in_id", sa.String(length=40), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=False),
        sa.Column("role", sa.Enum("USER", "COACH", name="message_role"), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["check_in_id"], ["coach_check_ins.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_coach_messages_check_in_created", "coach_messages", ["check_in_id", "created_utc"], unique=False
    )
    op.create_table(
        "coach_proposals",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("check_in_id", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.Enum("NUTRITION", "TRAINING", name="proposal_kind"), nullable=False),
        sa.Column("headline", sa.String(length=255), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("reviewer_note", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPLIED", "EDITED", "REJECTED", name="proposal_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["check_in_id"], ["coach_check_ins.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_coach_proposals_check_in", "coach_proposals", ["check_in_id"], unique=False)
    op.create_table(
        "workout_plan_exercises",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("plan_entry_id", sa.String(length=40), nullable=False),
        sa.Column("exercise_id", sa.String(length=40), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rest_seconds", sa.Integer(), nullable=False),
        sa.Column("planned_sets", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["plan_entry_id"], ["workout_plan_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workout_plan_exercises_entry",
        "workout_plan_exercises",
        ["plan_entry_id", "position"],
        unique=False,
    )
    op.create_table(
        "workout_sessions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=False),
        sa.Column("plan_entry_id", sa.String(length=40), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_entry_id"], ["workout_plan_entries.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workout_sessions_owner_started", "workout_sessions", ["owner_id", "started_at"], unique=False
    )
    op.create_table(
        "workout_set_logs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=False),
        sa.Column("exercise_id", sa.String(length=40), nullable=True),
        sa.Column("exercise_name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.Enum("WARMUP", "WORKING", name="set_kind"), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["workout_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workout_set_logs_exercise",
        "workout_set_logs",
        ["owner_id", "exercise_id", "position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workout_set_logs_exercise", table_name="workout_set_logs")
    op.drop_table("workout_set_logs")
    op.drop_index("ix_workout_sessions_owner_started", table_name="workout_sessions")
    op.drop_table("workout_sessions")
    op.drop_index("ix_workout_plan_exercises_entry", table_name="workout_plan_exercises")
    op.drop_table("workout_plan_exercises")
    op.drop_index("ix_coach_proposals_check_in", table_name="coach_proposals")
    op.drop_table("coach_proposals")
    op.drop_index("ix_coach_messages_check_in_created", table_name="coach_messages")
    op.drop_table("coach_messages")
    op.drop_index("uq_workout_plan_owner_day", table_name="workout_plan_entries")
    op.drop_table("workout_plan_entries")
    op.drop_index("uq_weigh_ins_owner_date", table_name="weigh_ins")
    op.drop_table("weigh_ins")
    op.drop_table("profiles")
    op.drop_index("ix_foods_owner_name", table_name="foods")
    op.drop_table("foods")
    op.drop_index("ix_food_entries_owner_date", table_name="food_entries")
    op.drop_table("food_entries")
    op.drop_index("ix_exercises_owner_name", table_name="exercises")
    op.drop_table("exercises")
    op.drop_index("ix_coach_check_ins_owner_created", table_name="coach_check_ins")
    op.drop_table("coach_check_ins")
    op.drop_index("uq_users_email", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
